application: trusty-catbird-645
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: assets

- url: /(fc/fc2/bis/tg/fr/ir/bot2)/task/
  script: phicops.wsgi.application
  login: admin

#- url: /fc/task/update_all/
#  script: phicops.wsgi.application
#  login: admin
  
#- url: /bis/task/eers_update/
#  script: phicops.wsgi.application
#  login: admin

#- url: /tg/task/update/
#  script: phicops.wsgi.application
#  login: admin

- url: /.*
  script: phicops.wsgi.application

libraries:
- name: PIL
  version: latest

- name: lxml
  version: "latest"  

- name: numpy
  version: "latest"  

- name: django
  version: "1.5"
  