application: trusty-catbird-645
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: assets

- url: /.*
  script: phicops.wsgi.application

libraries:
- name: PIL
  version: latest

- name: lxml
  version: "latest"  

- name: django
  version: "1.5"
  