FIELD_DATE = 0
FIELD_CURRENCY_NAME = 1
FIELD_BUY_NAME = 2
FIELD_BUY_CASH = 3
FIELD_BUY_ON_DEMAND = 4
FIELD_SELL_NAME = 5
FIELD_SELL_CASH = 6
FIELD_SELL_ON_DEMAND = 7

CURRENCY_JPY = 'JPY'
CURRENCY_USD = 'USD'
CURRENCY_CNY = 'CNY'
CURRENCY_TWD = 'TWD'

from datetime import date
MONTH_DAY_BEGIN = 1
MONTH_DAY_MIDDLE = 15
MONTH_DAY_END = -1
MONTH_DAY_TODAY = date.today().day